# Site settings
title: RiboKit
email: ribokit.info@gmail.com
description: ""
baseurl: ""
url: "http://ribokit.github.io"
github_username:  ribokit

# Default variables
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      level: 1
      title: ""
      author: "Siqi Tian"
      ga_tracker: UA-36037648-6
  -
    scope:
      path: "redirect"
    values:
      layout: "redirect"
      sitemap: false
      title: "Redirect"
  -
    scope:
      path: "workflows"
    values:
      title: "Workflow"
      level: 2
      author: "Rhiju Das"
      root: "/"
  -
    scope:
      path: "docs"
    values:
      title: "Doc Standards"
      description: "Internal Guideline on Writing <u>St</u>an<u>d</u>ards"
      root: "/docs/"
  -
    scope:
      path: "repos/ribovis"
    values:
      title: "RiboVis"
      description: "PyMOL Commands by the Das Lab Style"
      repo: "ribokit/RiboVis"
      author: "Siqi Tian"
      root: "/RiboVis/"
  -
    scope:
      path: "repos/ribopaint"
    values:
      title: "RiboPaint"
      description: "Paint Secondary Structure Diagrams"
      repo: "ribokit/RiboPaint"
      author: "Siqi Tian"
      root: "/RiboPaint/"

# Build settings
markdown: kramdown
permalink: pretty


# Markdown Processors
kramdown:
  input: GFM

  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

  # coderay:
  #   coderay_wrap:              div
  #   coderay_line_numbers:      inline
  #   coderay_line_number_start: 1
  #   coderay_tab_width:         4
  #   coderay_bold_every:        10
  #   coderay_css:               style


# Redirect url
# gems:
#   - jekyll-redirect-from

# whitelist:
#   - jekyll-redirect-from
